"""Shared pytest fixtures for the AGEVP API test suite."""

import os
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

# Ensure ANTHROPIC_API_KEY is set before any api module is imported.
# Tests never make real network calls; this just satisfies the config-level
# os.environ lookup at import time.
os.environ.setdefault("ANTHROPIC_API_KEY", "test-key-not-real")

from api.main import app  # noqa: E402  (must come after env var is set)


# ---------------------------------------------------------------------------
# Populated event-context.md text used across tests
# ---------------------------------------------------------------------------
POPULATED_EVENT_CONTEXT = """\
# Event Context — AGEVP

**Name:** Summer Gala 2026
**Date:** 2026-08-15
**Type:** gala
**Expected attendance:** 200
**Fixed budget:** €15000
**Event lead:** Alice Dupont
**Preferred area:** Paris 8e
**Constraints / notes:** No outdoor spaces

---
*Generated by session-init — not versioned*
"""

BLANK_EVENT_CONTEXT = """\
# Event Context — AGEVP

**Name:** [TBD]
**Date:** [TBD]
**Type:** [festival / sports / cultural / workshop / gala / other]
**Expected attendance:** [TBD]
**Fixed budget:** €[TBD]
**Event lead:** [TBD]
**Preferred area:** [Paris — arrondissement or neighbourhood]
**Constraints / notes:** [TBD]

---
*Generated by session-init — not versioned*
"""

SAMPLE_DRAFT_FRONTMATTER = """\
---
to: venue@example.com
subject: Inquiry
purpose: venue_inquiry
status: draft
---

Body text here.
"""


@pytest.fixture()
def tmp_project_root(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Create a minimal project directory tree and patch all config paths."""
    # Create directory structure
    (tmp_path / "drafts").mkdir()
    (tmp_path / "doc-content").mkdir()
    (tmp_path / "output").mkdir()
    (tmp_path / ".claude" / "agents").mkdir(parents=True)

    # Write a populated event-context.md
    event_ctx = tmp_path / "event-context.md"
    event_ctx.write_text(POPULATED_EVENT_CONTEXT, encoding="utf-8")

    # Patch every path constant that file_store.py and config.py expose
    import api.config as cfg
    import api.services.file_store as fs

    monkeypatch.setattr(cfg, "PROJECT_ROOT", tmp_path)
    monkeypatch.setattr(cfg, "AGENTS_DIR", tmp_path / ".claude" / "agents")
    monkeypatch.setattr(cfg, "DRAFTS_DIR", tmp_path / "drafts")
    monkeypatch.setattr(cfg, "DOC_CONTENT_DIR", tmp_path / "doc-content")
    monkeypatch.setattr(cfg, "OUTPUT_DIR", tmp_path / "output")
    monkeypatch.setattr(cfg, "EVENT_CONTEXT_PATH", event_ctx)
    monkeypatch.setattr(cfg, "SCRIPTS_DIR", tmp_path / "scripts")

    # Patch the same names as imported directly into file_store
    monkeypatch.setattr(fs, "DRAFTS_DIR", tmp_path / "drafts")
    monkeypatch.setattr(fs, "DOC_CONTENT_DIR", tmp_path / "doc-content")
    monkeypatch.setattr(fs, "OUTPUT_DIR", tmp_path / "output")
    monkeypatch.setattr(fs, "EVENT_CONTEXT_PATH", event_ctx)

    return tmp_path


@pytest.fixture()
def client() -> TestClient:
    """Return a synchronous TestClient for the FastAPI app."""
    return TestClient(app)
