import re
from pathlib import Path

import yaml
from fastapi import HTTPException

from api.config import (
    DRAFTS_DIR,
    DOC_CONTENT_DIR,
    OUTPUT_DIR,
    EVENT_CONTEXT_PATH,
)
from api.models import Draft, DraftSummary, OutputFile, PipelineStatus

# Keys in event-context.md (order preserved)
_CONTEXT_KEYS: list[tuple[str, str]] = [
    ("Name", "name"),
    ("Date", "date"),
    ("Type", "type"),
    ("Expected attendance", "expected_attendance"),
    ("Fixed budget", "fixed_budget"),
    ("Event lead", "event_lead"),
    ("Preferred area", "preferred_area"),
    ("Constraints / notes", "constraints"),
]

_TBD_RE = re.compile(r"^\[.*\]$")


def read_event_context() -> dict:
    text = EVENT_CONTEXT_PATH.read_text(encoding="utf-8")
    result: dict = {}
    for md_key, field in _CONTEXT_KEYS:
        pattern = re.compile(
            r"^\*\*" + re.escape(md_key) + r"\:\*\*\s*(.*)$", re.MULTILINE
        )
        match = pattern.search(text)
        raw = match.group(1).strip() if match else ""
        result[field] = "" if _TBD_RE.match(raw) else raw
    return result


def write_event_context(data: dict) -> None:
    lines: list[str] = ["# Event Context — AGEVP\n"]
    field_map = {field: md_key for md_key, field in _CONTEXT_KEYS}
    for field, md_key in field_map.items():
        value = data.get(field, "")
        lines.append(f"**{md_key}:** {value or '[TBD]'}")
    lines.append("\n---")
    lines.append("*Generated by session-init — not versioned*\n")
    EVENT_CONTEXT_PATH.write_text("\n".join(lines), encoding="utf-8")


def _parse_draft(path: Path) -> Draft:
    text = path.read_text(encoding="utf-8")
    if text.startswith("---"):
        parts = text.split("---", 2)
        frontmatter = yaml.safe_load(parts[1]) if len(parts) >= 3 else {}
        body = parts[2].strip() if len(parts) >= 3 else ""
    else:
        frontmatter = {}
        body = text.strip()

    fm = frontmatter or {}
    return Draft(
        name=path.stem,
        purpose=str(fm.get("purpose", "")),
        to=str(fm.get("to", "")),
        subject=str(fm.get("subject", "")),
        status=str(fm.get("status", "draft")),
        body=body,
    )


def list_drafts() -> list[DraftSummary]:
    if not DRAFTS_DIR.exists():
        return []
    summaries: list[DraftSummary] = []
    for path in sorted(DRAFTS_DIR.glob("*.md")):
        draft = _parse_draft(path)
        summaries.append(
            DraftSummary(
                name=draft.name,
                purpose=draft.purpose,
                to=draft.to,
                subject=draft.subject,
                status=draft.status,
            )
        )
    return summaries


def read_draft(name: str) -> Draft:
    path = DRAFTS_DIR / f"{name}.md"
    if not path.exists():
        raise HTTPException(status_code=404, detail=f"Draft '{name}' not found")
    return _parse_draft(path)


def list_doc_content() -> list[str]:
    if not DOC_CONTENT_DIR.exists():
        return []
    return sorted(p.name for p in DOC_CONTENT_DIR.glob("*.json"))


def list_output() -> list[OutputFile]:
    if not OUTPUT_DIR.exists():
        return []
    files: list[OutputFile] = []
    for path in sorted(OUTPUT_DIR.iterdir()):
        if path.is_file():
            files.append(
                OutputFile(
                    name=path.name,
                    type=path.suffix.lstrip("."),
                    path=str(path),
                )
            )
    return files


def pipeline_status() -> PipelineStatus:
    ctx = read_event_context()
    event_configured = any(v for v in ctx.values())
    drafts = list_drafts()
    return PipelineStatus(
        event_configured=event_configured,
        drafts_count=len(drafts),
        doc_content_count=len(list_doc_content()),
        output_count=len(list_output()),
        draft_names=[d.name for d in drafts],
    )
